### ISSUE TITLE
win 10 support?

### ISSUE THREAD

**Issue by cadon** [thebarbershopper/bombly#13]
dragonfly does not work in win10 anymore, are there alternative speech recognition programs this bombly would work with?

**Comment by ghost** [comment]
Works fine for me on Windows 10. Make sure you're following the install instructions on the bombly readme, you need to install from the dragonfly source.

**Comment by cadon** [comment]
Thanks, tried that, but got this message

```
C:\Users\cadon\Desktop\dragonfly-master>python setup.py install
Traceback (most recent call last):
  File "setup.py", line 21, in <module>
    from ez_setup import use_setuptools
  File "C:\Users\cadon\Desktop\dragonfly-master\ez_setup.py", line 98
    except pkg_resources.VersionConflict, e:
                                        ^
SyntaxError: invalid syntax
```

My version of python is 3.5. I read that Win10 has no open speech recognition anymore thanks to cortana, so do I need an extra program for that?

**Comment by ghost** [comment]
Dragonfly does not work with Python 3, you need to use Python 2

**Comment by cadon** [comment]
Ok great, that solved it, thanks! Is it nowhere written and common knowledge (I'm new to python) or did I just miss that information?

**Comment by mutabledevotions** [comment]
Just discovered that as well. It's the fact that the python update deprecated the use of , e and replaced it with "as."
