### ISSUE TITLE
Wire sequence letters

### ISSUE THREAD

**Issue by tyrope** [thebarbershopper/bombly#14]
Some people use the NATO alphabet, some use greek, either way, the words that would mark position vary between groups and shouldn't be hard to implement:
- Apple, Alpha
- Bravo, Beta
- Charlie(, Gamma, though not commonly used because it's C not G.)

You're missing: Alpha and Beta (and Gamma?)

**Comment by dopeghoti** [comment]
I'd imagine that Gamma would be used for G; Greek doesn't have a 'C' per se to use, however (Gamma is simply the third letter of the Greek alphabet).  I think I already submitted a patch to use the NATO alphabet a while ago, though:  https://github.com/ctfhacker/bombly/pull/3
