### ISSUE TITLE
Robot Overlord Celebration

### ISSUE THREAD

**Issue by mertzjames** [thebarbershopper/bombly#2]
The ending of a robot defusal is rather anti-climatic.  When the bomb is defused, I want a response of:

"I AM YOUR BOMB DEFUSING OVERLORD!"

**Comment by QuinnWilton** [comment]
+1

**Comment by ctfhacker** [comment]
Here we go: 

https://github.com/thebarbershopper/bombly/commit/f7bf4c9d1876e7bf0d5efd43e5a57be60243fd97

**Comment by ctfhacker** [comment]
The more easter eggs the better!
